### ISSUE TITLE
[Bug]: Custom scrollbar causing layout shifts

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#1083]
### What happened?

The custom scrollbar is causing the website's layout to shift on multiple occasions, like opening a modal or searching for something (depends on screen size)

https://github.com/movie-web/movie-web/assets/100528712/f620beb1-c6fe-43b2-ba9c-8f70f9d0d721

**Comment by sussy-code** [comment]
i fixed this on my /discover page using this in my index.css
```css
html,
body {
  @apply bg-background-main font-main text-type-text;
  min-height: 100vh;
  min-height: 100dvh;
  font-size: 1.0235em;
  scrollbar-width: none; /* Hide scrollbar for Firefox */
  -ms-overflow-style: none; /* Hide scrollbar for Internet Explorer and Edge */
}
```
see it [here](https://sudo-flix.lol/discover)
